apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-b-hpa
  namespace: service-b
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-b
  minReplicas: 1          # Keep at least 1 pod (less critical service)
  maxReplicas: 4          # Scale up to max 4 pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80    # Scale when CPU > 80% (higher threshold)