apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-allow-service-a
  namespace: redis
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
  - Ingress  # Only ingress needed!
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: service-a
    ports:
    - protocol: TCP
      port: 6379