apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: service-a
  labels:
    app: service-a
spec:
  selector:
    app: service-a
  ports:
  - name: http
    protocol: TCP
    port: 80        # External port (what ingress connects to)
    targetPort: 8080 # Pod port (what your app actually runs on)
  type: ClusterIP