apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: service-b
  name: service-b-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]